---
abstract: '[DEPRECATED] Selectively upgrade a few modules to depend on the version used.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: '1.003001'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::DZil: '0'
  Test::More: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Author-KENTNL-Prereqs-Latest-Selective
provides:
  Dist::Zilla::Plugin::Author::KENTNL::Prereqs::Latest::Selective:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/Prereqs/Latest/Selective.pm
    version: '1.001001'
recommends:
  Moose: '2.000'
requires:
  Dist::Zilla::Role::PrereqSource: '0'
  Module::Data: '0'
  Moose: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-Prereqs-Latest-Selective/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-Prereqs-Latest-Selective
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-Prereqs-Latest-Selective.git
version: '1.001001'
